// <auto-generated />
using CodeBaseFirstApproach.Model.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeBaseFirstApproach.Model.Migrations
{
    [DbContext(typeof(UserDbcontext))]
    [Migration("20230726061020_CodeFirstAddclass")]
    partial class CodeFirstAddclass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeBaseFirstApproach.Model.Models.RegistartionModels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Fullname")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Fullname");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Password");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Phonenumber");

                    b.Property<int>("Standard")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("UserRegistration");
                });
#pragma warning restore 612, 618
        }
    }
}
